version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Critical: Install your actual Python package
python:
  install:
    - method: pip
      path: .  # Install your package in editable mode
    - requirements: docs/requirements.txt  # Additional doc dependencies