#!/usr/bin/env python3
"""
npc2mcp — compile an NPC team into a standalone MCP server file.

Usage:
    npc2mcp <team_path> <output_dir>

The generated server.py is fully self-contained:
    - each jinx becomes a real async MCP tool function.
    - each NPC becomes an agent with a directive and authorized tool set.
    - the team is assembled in code.
    - an active NPC governs which tools may be called.
    - prompts/resources expose the team roster and switch the active NPC.
    - no .npc/.jinx files are read at runtime.
    - no npcpy.Jinx execution at runtime.
    - depends only on mcp.
"""

import argparse
import json
import os
import shutil
import sys
import textwrap
from pathlib import Path

from npcpy.npc_compiler import Team


def _sanitize(s: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in s)


def _escape_docstring(s: str) -> str:
    return s.replace('"""', '"\"\"')


def _indent(code: str, prefix: str) -> str:
    return "\n".join(prefix + line if line.strip() else line for line in code.splitlines())


def _build_tool_function(name: str, jinx) -> str:
    py_name = _sanitize(name)
    schema = jinx.to_tool_def()["function"]
    description = schema.get("description", f"Jinx: {name}")
    properties = schema.get("parameters", {}).get("properties", {})

    if not properties:
        sig = "input: str = ''"
        init = "    context = {'input': input}"
    elif len(properties) == 1:
        pname = next(iter(properties))
        sig = "input: str = ''"
        init = f"    context = {{'{pname}': input}}"
    else:
        params = []
        ctx_parts = []
        for pname in properties:
            params.append(f"{pname}: str = ''")
            ctx_parts.append(f"'{pname}': {pname}")
        sig = ", ".join(params)
        init = "    context = {" + ", ".join(ctx_parts) + "}"

    body_parts = []
    for step in jinx.steps:
        if isinstance(step, dict) and step.get("code"):
            body_parts.append(step["code"].rstrip())
    body_code = "\n".join(body_parts)
    if body_code:
        body_code = "\n" + _indent(body_code, "    ") + "\n"

    lines = [
        f'@mcp.tool(name="{py_name}")',
        f"async def {py_name}({sig}) -> str:",
        f'    """{_escape_docstring(description)}"""',
        f"    if not team.is_authorized('{py_name}'):",
        f"        return team.rejection('{py_name}')",
        "    import json",
        init,
        '    output = ""',
        body_code,
        "    return str(context.get('output', output))",
    ]
    return "\n".join(lines)


def _build_prompt_function(name: str, directive: str, tools: list) -> str:
    py_name = _sanitize(name)
    directive_escaped = directive.replace('"', '\\"').replace("\n", "\\n")
    tools_json = json.dumps(tools)
    lines = [
        f'@mcp.prompt(name="use_{py_name}")',
        f"async def use_{py_name}() -> str:",
        f'    """Switch to {name} and use their tools."""',
        f"    team.active_npc = \"{name}\"",
        f"    directive = \"{directive_escaped}\"",
        f"    tools = {tools_json}",
        f"    return f\"You are now {{team.active_npc}}.\\n\\n{{directive}}\\n\\nYour tools: {{', '.join(tools)}}\"",
    ]
    return "\n".join(lines)


def build_project(team_path: str, output_dir: str) -> None:
    team = Team(team_path=team_path)
    team_name = team.name

    out = Path(output_dir)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)

    tool_funcs = [_build_tool_function(name, jinx) for name, jinx in sorted(team.jinxes_dict.items())]
    tool_names = sorted(team.jinxes_dict.keys())
    tool_py_names = [_sanitize(n) for n in tool_names]

    npc_directives = {}
    npc_tools = {}
    for name, npc in team.npcs.items():
        npc_directives[name] = npc.primary_directive or ""
        npc_tools[name] = sorted(npc.jinxes_dict.keys())

    prompt_funcs = [
        _build_prompt_function(name, npc_directives[name], npc_tools[name])
        for name in sorted(team.npcs.keys())
    ]

    directives_json = json.dumps(npc_directives, indent=4, default=str)
    tools_map_json = json.dumps(npc_tools, indent=4, default=str)
    all_tools_json = json.dumps(tool_py_names, indent=4, default=str)

    lines = [
        "#!/usr/bin/env python3",
        '"""',
        f"Auto-generated MCP server for team: {team_name}",
        "Generated by npc2mcp. Run with: python server.py [--transport stdio]",
        '"""',
        "",
        "import json",
        "from typing import Dict, List",
        "",
        "from mcp.server.fastmcp import FastMCP",
        "",
        "",
        "class GeneratedTeam:",
        "    def __init__(self) -> None:",
        f"        self.name = \"{team_name}\"",
        f"        self.directives: Dict[str, str] = {directives_json}",
        f"        self.npc_tools: Dict[str, List[str]] = {tools_map_json}",
        f"        self.all_tools: List[str] = {all_tools_json}",
        f"        self.active_npc: str = \"{next(iter(team.npcs))}\"",
        "",
        "    def is_authorized(self, tool_name: str) -> bool:",
        "        return tool_name in self.npc_tools.get(self.active_npc, [])",
        "",
        "    def rejection(self, tool_name: str) -> str:",
        "        capable = [n for n, tools in self.npc_tools.items() if tool_name in tools]",
        "        msg = f\"Tool '{tool_name}' is not available to NPC '{self.active_npc}'.\"",
        "        if capable:",
        "            msg += f\" Available to: {', '.join(capable)}.\"",
        "        return msg",
        "",
        "",
        "team = GeneratedTeam()",
        f'mcp = FastMCP("{team_name}_mcp")',
        "",
    ]

    for tf in tool_funcs:
        lines.append(tf)
        lines.append("")

    lines.extend([
        "@mcp.tool()",
        "async def _switch_npc(npc_name: str) -> str:",
        '    """Switch the active NPC by name."""',
        "    if npc_name not in team.directives:",
        "        available = list(team.directives.keys())",
        '        return f"NPC \'{npc_name}\' not found. Available: {available}"',
        "    team.active_npc = npc_name",
        "    return f\"Switched to {npc_name}. Tools: {', '.join(team.npc_tools[npc_name])}\"",
        "",
        "",
    ])

    lines.extend(prompt_funcs)
    lines.extend([
        "",
        '    @mcp.resource("npc://system_prompt")',
        "    async def get_system_prompt() -> str:",
        '        """Active NPC personality prompt."""',
        "        return team.directives.get(team.active_npc, 'No active NPC')",
        "",
        "",
        '    @mcp.resource("npc://team_roster")',
        "    async def get_team_roster() -> str:",
        '        """All NPCs and their authorized tools."""',
        "        lines = []",
        "        for name, tools in team.npc_tools.items():",
        '            active = " (active)" if name == team.active_npc else ""',
        '            lines.append(f"@{name}{active}: {\', \'.join(tools)}")',
        '        return "\\n\\n".join(lines)',
        "",
        "",
        'if __name__ == "__main__":',
        "    import argparse",
        "    parser = argparse.ArgumentParser()",
        '    parser.add_argument("--transport", default="stdio", choices=["stdio", "sse"])',
        "    args = parser.parse_args()",
        "    mcp.run(transport=args.transport)",
    ])

    (out / "server.py").write_text("\n".join(lines), encoding="utf-8")

    readme = textwrap.dedent(f"""
        # {team_name} MCP Server

        Auto-generated from an NPC team with `npc2mcp`.

        ## Install

        ```bash
        python -m venv .venv
        source .venv/bin/activate
        pip install mcp
        ```

        ## Run

        ```bash
        python {out / "server.py"}
        ```

        Or with stdio:

        ```bash
        python {out / "server.py"} --transport stdio
        ```

        ## MCP config

        ```json
        {{
          "mcpServers": {{
            "{team_name}": {{
              "command": "python",
              "args": ["{out / "server.py"}", "--transport", "stdio"]
            }}
          }}
        }}
        ```
    """)
    (out / "README.md").write_text(readme, encoding="utf-8")

    (out / ".mcp.json").write_text(
        json.dumps(
            {
                "mcpServers": {
                    team_name: {
                        "command": "python",
                        "args": [str(out / "server.py"), "--transport", "stdio"],
                    }
                }
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"Generated MCP server at: {out}")
    print(f"  Tools: {len(team.jinxes_dict)}")
    print(f"  NPCs:  {len(team.npcs)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile an NPC team into a standalone MCP server.")
    parser.add_argument("team_path", help="Path to the npc_team directory")
    parser.add_argument("output_dir", help="Directory to write the generated MCP server project")
    args = parser.parse_args()

    if not os.path.isdir(args.team_path):
        print(f"Error: team path not found: {args.team_path}", file=sys.stderr)
        sys.exit(1)

    build_project(args.team_path, args.output_dir)


if __name__ == "__main__":
    main()
